### ISSUE TITLE
Why is "break" not implemented in "each"?

### ISSUE THREAD

**Issue by Nasicus** [jashkenas/underscore#2247] opened 2015-07-27 11:35 UTC
Hey

Why is the `each` method not implemented so, that a break (or a "pseudo break") can be used?

I know you can make use of "break" by using `any` or `some` - however I find it strange to use these methods just for iterating.

Why don't we change the implementation to something like this:

	  _.each = _.forEach = function (obj, iteratee, context) {
		var breakString = "break";
		iteratee = optimizeCb(iteratee, context);
		var i, length;
		if (isArrayLike(obj)) {
		  for (i = 0, length = obj.length; i < length; i++) {
			if (iteratee(obj[i], i, obj) === breakString) {
			  break;
			}
		  }
		} else {
		  var keys = _.keys(obj);
		  for (i = 0, length = keys.length; i < length; i++) {
			if (iteratee(obj[keys[i]], keys[i], obj) === breakString) {
			  break;
			}
		  }
		}
		return obj;
	  };

By using the new implementation, you could write something like this:

	_.each([0,1,2,3], function(i){
		//continue loop (this already works)
		if (i == 0){
			return "continue"; //or just return;
		}

		console.log(i);

		//break loop (this would be new)
		if (i == 2){
			return "break";
		}
	});

Additionally we could even introduce a string "constant" à la `_.forBreakValue`.

Would this be a performance issue? Or is this considered "bad design" because we would have to rely on a "string" which is returned?

Thanks & Greetings

**Comment by megawac** [comment] 2015-07-27 12:04
Duplicate of #1545

**Closed by megawac** 2015-07-27 12:04 UTC
