### ISSUE TITLE
_.ieEqual doesn't work with objects whose value is a Set

### ISSUE THREAD

**Issue by aswathkk** [jashkenas/underscore#2889] opened 2020-11-19 12:07 UTC
Here's the example which was failing for me:
```
_.isEqual({a:new Set([1,2])}, {a: new Set([1])})
// returns true
```

**Comment by jgonggrijp** [comment] 2020-11-20 23:07
Duplicate of #2451 and by extension, #2147.

**Closed by jgonggrijp** 2020-11-20 23:07 UTC

**Comment by jgonggrijp** [comment] 2020-11-20 23:09
By the way, support for `Map`, `Set` and iterables is planned for version 2.0.
