### ISSUE TITLE
isNumber of NaN returning true 

### ISSUE THREAD

**Issue by somanos** [jashkenas/underscore#2175] opened 2015-05-12 20:52 UTC
Hi there,
the statement _.isNumber(parseInt(null)) returns true
Yes, typeof(NaN) returns "number", but does it sounds fine to say something is a number whereas it is not is not a number ?

**Comment by jridgewell** [comment] 2015-05-12 20:57
Dupe of [many](https://github.com/jashkenas/underscore/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+nan+isnumber).

`NaN` _is_ a number. You're probably looking for `_.isFinite`.

**Closed by jridgewell** 2015-05-12 20:57 UTC

**Comment by somanos** [comment] 2015-05-12 21:05
Nop. I was looking for _.isNaN, which bears a less confusing meaning...
