### ISSUE TITLE
underscore@1.13.5 - patch-package not found

### ISSUE THREAD

**Issue by vfidelix** [jashkenas/underscore#2971] opened 2022-09-23 21:01 UTC
I'm founding problems when trying to compile my project with the 1.13.5 version.

`npm ERR! sh: 1: patch-package: not found`

![image](https://user-images.githubusercontent.com/11541680/192056035-4958e88b-9b2c-44b1-8d92-204896d650aa.png)

**Comment by dpavancini** [comment] 2022-09-23 21:04
Same here
Exit code: 127
Command: patch-package

**Comment by joeycozza** [comment] 2022-09-23 21:11
Duplicate of https://github.com/jashkenas/underscore/issues/2967

**Comment by jgonggrijp** [comment] 2022-09-23 22:22
I just released 1.13.6, hopefully that fixes it. Please close if that is the case.

**Closed** 2022-09-23 22:54 UTC
