### ISSUE TITLE
proposal: _.sum

### ISSUE THREAD

**Issue by markbrown4** [jashkenas/underscore#2165] opened 2015-04-30 00:08 UTC
A summing function seems like a worthy addition to Underscore to me, I know it can be done with reduce but I've found to be the largest need to use reduce.

```coffee
_.reduce lineItems, (previous, lineItem)->
  previous + lineItem.quantity
, 0

# could be much simpler
_.sum lineItems, (lineItem)-> lineItem.quantity
```

Here's an implementation:

```coffee
_.sum = (iteratee, func)->
  _.reduce iteratee, (previous, current)->
    previous + func(current)
  , 0

```

**Comment by akre54** [comment] 2015-04-30 12:17
Duplicate of #460 (see also #1433)

**Closed by akre54** 2015-04-30 12:17 UTC
Labels: duplicate

**Comment by markbrown4** [comment] 2015-04-30 22:18
Thanks, can you give an example of how to use _.iteratee here?

I understand the reasoning but disagree, the utility of utility functions get lost if the meaning is abstracted away.  If a theoretical 50% of uses of _.reduce were for sum then why make each person re-invent the wheel and make the implementation less clear?

I'm a little surprised this basic feature isn't available natively in `Array.prototype.sum` or `Math.sum`, perhaps along the same lines of reasoning, a for loop of reduce both allow for this.

**Comment by akre54** [comment] 2015-05-01 15:29
We can't cover every use case, and we shouldn't attempt to. It's much cleaner, clearer and easier to build these functions yourself using the functional programming building blocks Underscore gives you. You might also want to look into add-on libraries that [`mixin`](http://underscorejs.org/#mixin) to Underscore like [Underscore-contrib](http://documentcloud.github.io/underscore-contrib/) or the [mixin catalog](https://github.com/jashkenas/underscore/wiki/Mixin-Catalog).
