### ISSUE TITLE
ES modules exports

### ISSUE THREAD

**Issue by mjeanroy** [jashkenas/underscore#2718] opened 2017-12-30 16:30 UTC
Hi,

Is there a plan to migrate to ES Modules in the future or do you consider it worthless? It would be great to be able to import individual methods using ES imports, allowing tree-shaking and many other build optimization.

I'm sorry if this question has already been asked, but I searched in issue and could not find anything about it. Thanks for all the work behind underscore!

**Comment by Kelichao** [comment] 2018-03-06 01:52
Feel it is not there yet

**Comment by unquietwiki** [comment] 2018-03-24 02:03
I was able to add **module exports { _ }** to the end of my underscore.js file, to at least resolve the error message for importing as **import _ from 'underscore.js'**

**Comment by nebulousdog** [comment] 2018-03-30 00:19
would be awesome :+1:

**Comment by jashkenas** [comment] 2018-04-23 20:02
Is there any good way we can add module exports to the main file, while maintaining backwards compatibility with non-module-supporting versions of JavaScript?

**Comment by unquietwiki** [comment] 2018-04-23 21:13
However Babel does it?

**Comment by nebulousdog** [comment] 2018-04-23 21:16
maybe `core-js` is a good example, although probably too modular to directly follow https://github.com/zloirock/core-js

**Comment by mjeanroy** [comment] 2018-04-24 10:36
@jashkenas Thanks for your response.

I don't think that it is possible to add the import statements on top of the main file and maintaining backwards compatibility without any transpilation task.

The easiest solution, for me, would be to have a build task to translate import statements to UMD using babel and publish two versions of underscore: the first one with  `export` and a second one for `umd`.

**Comment by lohfu** [comment] 2020-01-17 11:58
@jashkenas what do you think of @mjeanroy's suggestion? i would be happy to help...

**Comment by jashkenas** [comment] 2020-01-17 17:42
> @jashkenas what do you think of @mjeanroy's suggestion? i would be happy to help...

Sure! I'd be happy to merge a PR that swaps to named exports for all of the Underscore functions, and also uses Rollup to publish a UMD version of the file.

**Comment by lohfu** [comment] 2020-01-17 17:46
@jashkenas very cool! do you want to keep the src in one single file or can functions be placed in individual files?

**Comment by jashkenas** [comment] 2020-01-17 17:51
One single file, please.

If we can keep the diff as small and the result as clean as possible, that would help greatly. Ideally, just adding named exports to the functions where they are — with Underscore itself as the default export.

**Comment by jgonggrijp** [comment] 2020-02-22 01:35
@lohfu @mjeanroy has either of you worked on this in the meanwhile? Otherwise I'm offering to adopt this.

**Comment by lohfu** [comment] 2020-02-22 16:53
@jgonggrijp unfortunately i have found no time to focus on this, so you are more than welcome to give it a go. if i find time in the near future to help out i will ping you and see how it is going. good luck, have fun!

**Comment by gogo765795** [comment] 2020-03-26 17:14
Duplicate of #

**Comment by jgonggrijp** [comment] 2020-04-07 21:10
Closed in #2826.

**Closed by jgonggrijp** 2020-04-07 21:10 UTC
Labels: enhancement
