### ISSUE TITLE
_.bindAll is attached to next screen 

### ISSUE THREAD

**Issue by Priya08Nirmal** [jashkenas/underscore#2772] opened 2018-07-11 06:44 UTC
Hi,

I used _.bindAll(this, "funcName"); to use this pointer in callback function. This function is callback for scroll event. 
The callback checks for scroll bar, if it is at the end of screen I load next set of data and this process happen till the data fetched from DB. 
This functionality works fine. However when I go to next pages the scroll event is still attached to previous screen. So along with current page content it start fetching data from DB when scroll reached end of screen. 
I want to unbind, _.bindAll but unfortunately didn't find any option to do so. 
Could you please help me on this. 

Thanks

**Comment by jgonggrijp** [comment] 2020-04-30 23:01
@Priya08Nirmal Thanks for reaching out.

There is no way to un-bind a bound function. This is inherent to JavaScript. You can however keep a reference to the unbound function in case you need it later. How to do this depends on the specifics of your code.

I'm closing this because it isn't really an issue with Underscore. But if you want, you can still comment after the issue is closed and I'll see whether I can give you some tips.

**Closed by jgonggrijp** 2020-04-30 23:01 UTC
