### ISSUE TITLE
_.isEmpty, _.size, etc. fail for ES2015 Set objects

### ISSUE THREAD

**Issue by jonathaneunice** [jashkenas/underscore#2627] opened 2016-11-14 21:59 UTC
Underscore returns incorrect results for `Set` objects. E.g. believes they are empty when they are not. I assume other Underscore functions for iteration, inclusion testing, and so on will similarly fail.

```
~$ node
> u = require('underscore')
...
> s = new Set()
Set {}
> u.isEmpty(s)
true
> s.add(44)
Set { 44 }
> u.isEmpty(s)
true
> u.size(s)
0
> u.VERSION
'1.8.3'
```

Several open issues mention ES2015 `Set` and `Map` (e.g. [this one](https://github.com/jashkenas/underscore/issues/2451)); none seem the same as this bug. Reading source for v1.9.0, it seems to rely on `defaultKeys` (alias for `Object.keys`). `Object.keys` does not produce keys for `Set` objects, so this is likely to fail in the same ways it does now. Similarly `_.size` seems to rely on the the `.length` property, which `Set` does not have; it has an idiosyncratic `.size` property instead, which the source does not seem to query.

`Set` objects are new, and seem very immature. Still, when JS fails to do the right thing, I look to Underscore to make things right, or at least a little more logical. Hoping that a near release can help wrangle the new structures.

**Comment by akre54** [comment] 2016-11-14 22:11
I agree. In the short term, we should have a logic branch for `_.isMap` and `_.isSet` and check for `obj.count`. Want to open a pull?

**Comment by jonathaneunice** [comment] 2016-11-18 17:46
Considering taking a crack at it. Slightly daunted by the need to redefine core functions (e.g. `getLength`, `nativeKeys`) to incorporate `Set` and `Map`, or to add alternative logic paths ("are we dealing with these newfangled types? Okay, well then...") to a wide variety of Underscore functions. It's a considerable surgery for a first-time contributor. Any guidance?

**Comment by captbaritone** [comment] 2016-11-24 23:14
@jonathaneunice Two tips I would give:

1. Trust the tests. We have very good test coverage. As long as all existing tests continue to pass, you can assume you haven't broken anything too meaningful.

2. Feel free to open incomplete pull requests for [early feedback](https://42floors.com/blog/startups/thirty-percent-feedback). If you are unsure if you are on the right track, we can point you in the right direction.

**Comment by jgonggrijp** [comment] 2020-04-22 00:07
Duplicate of #2147.

**Closed by jgonggrijp** 2020-04-22 00:07 UTC
