### ISSUE TITLE
underscorejs.org Feature Request - Link to annotated source next to each function description

### ISSUE THREAD

**Issue by mhavard999** [jashkenas/underscore#2169] opened 2015-05-07 12:45 UTC
On the home page of underscorejs.org, every function is described like this:
![image](https://cloud.githubusercontent.com/assets/1484098/7515271/9ed2fd0e-f493-11e4-89dc-8fcb6918ec44.png)
I think it would be convenient if there was a link to `_.findWhere` (for example) on the annotated source page somewhere in each description.  I personally think it would make the most sense to put such a link on the first line after `_.findWhere(list, properties)`.  The annotated source page is set up to link to each function in the fragment url - i.e. http://underscorejs.org/docs/underscore.html#section-33 takes you directly to the source for `_.invoke` instead of the very top of the page.

Now that I'm studying the home page more closely, I also think it would be convenient if the function description had the same "¶" characters that the annotated source has that link to the fragment url of the element's position on the page.  So in the screenshot above, a little "¶" character would appear when you hover your mouse to the left of the bold "findWhere" heading, and it would link to http://underscorejs.org/#findWhere.  You can already get these fragment urls from the sidebar, but this would be convenient if you are scrolling down the page without looking at the sidebar.

**Comment by megawac** [comment] 2015-05-07 12:49
Duplicate of #2019

**Comment by mhavard999** [comment] 2015-05-07 12:51
Ah okay.  I guess I only searched open issues before I posted.

**Closed** 2015-05-07 12:50 UTC
Labels: duplicate
