### ISSUE TITLE
Patch is a dev dependency in 1.13.5. 

### ISSUE THREAD

**Issue by markfoo1** [jashkenas/underscore#2969] opened 2022-09-23 20:44 UTC
Consumers who use underscore as a dependency rather than as a dev dependency fail in postinstall because patch package is not available.

**Comment by mjaggard** [comment] 2022-09-23 20:47
This has broken my build :(

**Comment by joeycozza** [comment] 2022-09-23 21:11
duplicate of https://github.com/jashkenas/underscore/issues/2967

**Comment by jgonggrijp** [comment] 2022-09-23 22:23
I just released 1.13.6, hopefully that fixes it. Please close if that is the case.

**Closed** 2022-09-23 22:53 UTC
Labels: duplicate
