### ISSUE TITLE
_.memoize hasher result cannot be a symbol.

### ISSUE THREAD

**Issue by jdalton** [jashkenas/underscore#2497] opened 2016-04-14 00:41 UTC
Because the `_.memoize` hasher is resolved with `'' +` it will throw an error if the hasher result is a Symbol. A similar issue exists in `createEscaper`.

**Comment by jdalton** [comment] 2016-04-14 00:44
A similar issue exists in `createEscaper`.

**Comment by CodeFalling** [comment] 2016-05-04 03:24
But `createEscaper` just won't work with `symbol`, what should we do here?

**Comment by blacklovebear** [comment] 2016-05-26 07:02
Does "memoize" spell wrong???  I'm confused

**Comment by jgonggrijp** [comment] 2020-04-22 00:18
Duplicate of #1862.

**Closed by jgonggrijp** 2020-04-22 00:18 UTC
