### ISSUE TITLE
isArrayLike has a bit problem?

### ISSUE THREAD

**Issue by Codedogdogdog** [jashkenas/underscore#2755] opened 2018-05-09 06:19 UTC
when i see the underscore's source, i find isArrayLike use very frequent. but i think isArrayLike has a bit problem.
```
if (isArrayLike(obj)) {
  for (i = 0, length = obj.length; i < length; i++) {
    iteratee(obj[i], i, obj);
  }
}
```
This is a part of _.each.

if obj has `length` property, and satisfied conditions, we use `_.each` or any other iterate function, the result is undefined, but it's not what i want. so i think this is a bug ?

if this has any other consider, pls tell me.

**Comment by captbaritone** [comment] 2018-05-10 21:13
Duplicate of https://github.com/jashkenas/underscore/issues/1590

**Closed by captbaritone** 2018-05-10 21:13 UTC
