### ISSUE TITLE
Modular import cause error in typescript apps

### ISSUE THREAD

**Issue by marzzy** [jashkenas/underscore#2975] opened 2022-10-14 11:27 UTC
As you can see in this [Codesand example,](https://codesandbox.io/s/react-typescript-underscore-efciu8) I try to use the modular import in a typescript project, it works, but cause the error below:

`Cannot find module 'underscore/modules/map' or its corresponding type declarations.ts`

**Comment by jgonggrijp** [comment] 2022-10-14 19:31
Thank you for reaching out, @marzzy.

I do not see the error you report. Where should I look?

![Schermafbeelding 2022-10-14 om 21 29 46](https://user-images.githubusercontent.com/1540185/195927223-44fef2ab-a52b-4d3b-8d38-ab9b09b7f6a2.png)

**Comment by marzzy** [comment] 2022-10-15 16:10
It takes 2-3 minutes to load fully, after that, the error will appear on the address part like this:

<img width="698" alt="Screenshot 2022-10-15 at 18 07 01" src="https://user-images.githubusercontent.com/20150023/195996585-6228ab05-66c7-4d00-b6f8-32aafcbadf1c.png">

**Comment by jgonggrijp** [comment] 2022-10-16 19:23
Thanks, I see it now. The problem is in `@types/underscore/package.json`, which forbids TypeScript from importing anything other than the monolithic version of the package (`exports` field):

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/underscore/package.json

Contrast this with Underscore's own `package.json`, which does allow module imports:

https://github.com/jashkenas/underscore/blob/master/package.json

Best solution is to report a bug to DefinitelyTyped, or to submit a pull request there with your own fix (if you have the patience and courage to work on that).

Easiest solution is to just use the monolithic interface; it's only 8 kB. Second easiest is to put a `// @ts-ignore` above the import, but this has the disadvantage that TS will not check the type of any function that you import the modular way.

**Comment by jgonggrijp** [comment] 2022-10-18 16:39
Closing this as the question seems answered. Please feel welcome to comment again, though.

**Closed by jgonggrijp** 2022-10-18 16:39 UTC
