### ISSUE TITLE
Suggestion: _.isEmpty() work with numbers and bool as well.

### ISSUE THREAD

**Issue by Sarke** [jashkenas/underscore#2586] opened 2016-09-07 08:27 UTC
I realize the it is meant for objects, but there's no reason it can't work for numbers and bool as well.

The following are what I would consider unexpected behavior:

    _.isEmpty(9999)
    true
    _.isEmpty(true)
    true

**Comment by Florian-R** [comment] 2016-09-07 08:30
Dupe of #432, #2272, #2133 and probably a [lot of others issues on isEmpty](https://github.com/jashkenas/underscore/search?utf8=%E2%9C%93&q=isEmpty)

**Comment by akre54** [comment] 2016-09-07 13:05
Yup yup. Thanks @Florian-R.

**Closed by akre54** 2016-09-07 13:05 UTC
Labels: duplicate
