### ISSUE TITLE
_.template doesn't work in 1.7 prod

### ISSUE THREAD

**Issue by Roland1975** [jashkenas/underscore#2006] opened 2015-01-11 20:29 UTC
For example: 
``` _.template('<%= a %>', { a: 1 })```
returns:
```function (n){return a.call(this,n,h)}```

The development version returns the expected result.

**Comment by megawac** [comment] 2015-01-11 20:52
Duplicate of #1928

**Closed by megawac** 2015-01-11 20:52 UTC
Labels: duplicate
