### ISSUE TITLE
[enhancement] partitionMuti

### ISSUE THREAD

**Issue by cabbage89** [jashkenas/underscore#2249] opened 2015-07-28 08:37 UTC
function  partitionMuti(array,every){

var  arr=[];
_.each(array,function(n,index){
         var rem = Math.floor(index / every);
         if (index% every == 0)
                 arr[rem] = [];
          arr[rem].push(n);
});
return arr;
}

**Comment by cabbage89** [comment] 2015-07-28 08:39
_.partitionMuti([1,2,3,4,5,6,7,8,9],3)   ==   [[1,2,3],[4,,5,6],[7,8,9]]

**Comment by jdalton** [comment] 2015-07-28 14:09
It's [_.chunk](https://github.com/lodash/lodash/blob/npm/array/chunk.js#L29-L44).

**Comment by megawac** [comment] 2015-07-28 14:15
Duplicate of #1891

**Closed** 2015-07-28 14:15 UTC
