### ISSUE TITLE
namespace underscore so you can use `_` mixins only within package code

### ISSUE THREAD

**Issue by faceyspacey** [jashkenas/underscore#2352] opened 2015-11-19 18:54 UTC
I have a bunch of package code where I mixed in a bunch of methods to underscore. They obviously can't go into the global scope for client code to accidentally call, so how can I accomplish this? 

I've tried a bunch of techniques, posted on stackoverflow, etc, and nothing is fully working. Perhaps it doesn't matter for client code because their mixins will overwrite mine, but then my mixin methods of the same names won't continue to work. 

Essentially I'd like to clone Underscore completely.

**Comment by jdalton** [comment] 2015-11-19 19:49
In lodash there's a method called [_.runInContext()](https://lodash.com/docs#runInContext) which allows create a pristine lodash instance to augment. I could see something like that being added to Underscore to support this.

**Comment by akre54** [comment] 2015-11-19 22:15
Dupe of #2001 #1612 #1920

**Closed by akre54** 2015-11-19 22:15 UTC
Labels: duplicate, enhancement

**Comment by jdalton** [comment] 2015-11-19 22:22
Closing an issue as a dupe doesn't actually resolve the users issue.

**Comment by akre54** [comment] 2015-11-19 22:27
The other issues cover the topic pretty thoroughly.

**Comment by jdalton** [comment] 2015-11-19 22:33
I don't see where a clear solution was found.

**Comment by faceyspacey** [comment] 2015-11-19 23:02
yea, if `_.noConflig` still will mean whatever I mixin exists wherever underscore exists, then it wasn't solved. The package author doesn't seem intent on providing this feature. I'm not sure how its value isnt absurdly clear--not to mention by all the duplicate issues you guys just closed. Seems like your most popular recurring issue ever! 

Anyway, adding yet more underscores before my methods is obviously an option. It's a bad option though when you use your mixin methods day in and day out, especially when the right answer is at least 2 underscores now instead of (i.e: `_.__myMethod`). 

Even if it's not officially supported, there has to be some work around. Ive tried all sorts of cloning underscore, and overriding the `mixin` method, the `chain` method, `nativeEach`, `each`, etc, called within these functions so that I could have a completely different underscore without having to send another 1500 lines of underscore code to clients which assign to another variable.

What's the hack here?? I don't care about no official support--i just need this done for my mega large super cool framework so that i don't clobber the underscore methods of all the client code/developers that will hopefully be using my framework. It's a complete Framework on top of Meteor by the way ;)

**Comment by michaelficarra** [comment] 2015-11-19 23:16
@faceyspacey You don't need our help to do this.

```html
<script src=underscore.js></script>
<script>
var myUnderscore = _.noConflict();
</script>
<script src=underscore.js></script>
```

Now you have a clean `_` and a `myUnderscore`, which you can mutate all you want.

**Comment by faceyspacey** [comment] 2015-11-19 23:20
the only thing is I'm using Meteor, which packages up all my code for me, and includes Underscore by default. I think i can come up with a solution though to inject underscore into the head--i'm not sure about the server though--in Meteor land I'd have to add another package which also has underscore and in that package export it as another variable.

Thanks brother, im gonna do that if push come comes to shove--but I still bet there gotta be something more natural, even if somewhat hacky.

**Comment by jdalton** [comment] 2015-11-19 23:32
If you have access to node guts you could:
```js
var underscore_one = require('underscore');
underscore_one.foo = 1;

delete require.cache[require.resolve('underscore')];
var underscore_two = require('underscore');
underscore_two.foo // undefined
```

That said, I'm not sure why Underscore doesn't provide an easier way to do this seeing as node/npm is a primary use case.

**Comment by faceyspacey** [comment] 2015-11-19 23:41
that does solve the server. i guess i have my fallback. thank you guys. 

...but yea, who closed this issue! reopen it lol. i quickly read the other closed issues--the original package author seems to be quite stubborn lol. just messin with you man, wherever you are. it does seem there are workarounds that don't involve tearing up the internals like the ones mentioned here. Why do we have to be so strict about the whole "a mixin is a mixin" thing, i.e. expect to get clobbered. Its ridiculous. My 2 cents.
